ktor:
    application:
        modules:
            - com.example.ApplicationKt.module
    deployment:
        port: 443


ai:
  python:
    baseUrl: "http://localhost:8090"
    apiKey: ""
    timeoutMs: 15000


jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
